# Site Settings
title: "Nilearn Dev Days 2020"
description: >
  Join the Nilearn development community and shape what's next
baseurl: "/bulma-clean-theme"
url: "https://www.elizabeth-dupre.com"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass